add_lunch_combo twisted_angler-userdebug
#add_lunch_combo twisted_bullhead-userdebug
add_lunch_combo twisted_flo-userdebug
add_lunch_combo twisted_hammerhead-userdebug
#add_lunch_combo twisted_mako-userdebug
add_lunch_combo twisted_shamu-userdebug