#add_lunch_combo twisted_angler-user
#add_lunch_combo twisted_bullhead-user
add_lunch_combo twisted_flo-user
add_lunch_combo twisted_flo-userdebug
add_lunch_combo twisted_hammerhead-user
add_lunch_combo twisted_hammerhead-userdebug
#add_lunch_combo twisted_mako-user
add_lunch_combo twisted_shamu-user
add_lunch_combo twisted_shamu-userdebug

