#!/bin/sh
#
# Super-mega crusher of doom
# Shrinks apks by running pngquant or pngcrush or optipng or pngout on png images
#
# Point APKCERTS at the full path to a generated apkcerts.txt file, such as:
# /home/shade/dev/sources/android-cm-eclair/out/target/product/dream_sapphire/obj/PACKAGING/target_files_intermediates/cyanogen_dream_sapphire-target_files-eng.shade/META/apkcerts.txt
#
# cyanogen - shade@chemlab.org
# ChrisSoyars - me@ctso.me
# Nougat fixes: Joe Maples - frap129@gmail.com

set -e
QUIET=1
BASE=`pwd`
TMPDIR=/tmp/crusher-$$

. $ANDROID_BUILD_TOP/vendor/twisted/tools/colors

if [ "$APKCERTS" = "" ];
then
    if [ "$TARGET_BUILD_VARIANT" = "userdebug" ]; then
       TARGET_BUILD_VARIANT="eng"
    elif [ "$TARGET_BUILD_VARIANT" = "user" ]; then
       TARGET_BUILD_VARIANT="eng"
    fi

    APKCERTS=$OUT/obj/PACKAGING/target_files_intermediates/$TARGET_PRODUCT-target_files-$TARGET_BUILD_VARIANT.$USER/META/apkcerts.txt
    if [ ! -f "$APKCERTS" ];
    then
        echo $red"Set APKCERTS to the path to your apkcerts.txt file"$txtrst
        exit 1;
    fi
fi

if [ ! -f "$APKCERTS" ];
then
    echo $red"Invalid path to apkcerts.txt, set APKCERTS to the correct path."$txtrst
fi

if [ "$(which pngquant)" != "" ];
then
    if [ "$(which optipng)" != "" ];
    then
        OPTSTRING='Quantizing and optimizing'
        optimize_png () {
            pngquant --speed 1 --force --ext .png $1 1> /dev/null 2> /dev/null;
            optipng -o7 $1 1> /dev/null 2> /dev/null;
        }
    else
        OPTSTRING='Quantizing'
        optimize_png () {
            pngquant --speed 1 --force --ext .png $1 1> /dev/null 2> /dev/null
        }
    fi
else
    if [ "$(which optipng)" != "" ];
    then
        OPTSTRING='Optimizing'
        optimize_png () {
            optipng -o7 $1 1> /dev/null 2> /dev/null;
        }
    else
        echo $red"Please install pngquant or optipng (or both, for improved crushing)"$txtrst
        exit 1;
    fi
fi

if [ "`which aapt`" = "" ];
then
    echo $red"Please ensure aapt is in your \$PATH"$txtrst
    exit 1;
fi

if [ "`which zipalign`" = "" ];
then
    echo $red"Please ensure zipalign is in your \$PATH"$txtrst
    exit 1;
fi

if [ -e "$1" ];
then
    NAME=`basename $1`;
    echo $cya$OPTSTRING $ylw"$NAME..."$txtrst;

    if [ "$2" != "" ];
    then
        CERT=build/target/product/security/$2.x509.pem
        KEY=build/target/product/security/$2.pk8
        if [ ! -f "$ANDROID_BUILD_TOP/$CERT" ];
        then
            echo $red"$CERT does not exist!";$txtrst
            exit 1;
        fi
    else
        APKINFO=`grep "name=\"$NAME\"" $APKCERTS`;
        [ $QUIET ] || echo "APKINFO: $APKINFO";
        if [ "$APKINFO" = "" ];
        then
            echo $red"No apk info for $NAME";$txtrst
            exit 1;
        fi
        CERT=`echo $APKINFO | awk {'print $2'} | cut -f 2 -d "=" | tr -d "\""`;
        KEY=`echo $APKINFO | awk {'print $3'} | cut -f 2 -d "=" | tr -d "\""`;
        if [ "$CERT" = "" ];
        then
            echo -e $red"Unable to find certificate for $NAME"$txtrst
            exit 1;
        fi
        if [ "$CERT" = "PRESIGNED" ];
        then
            echo $grn"$NAME is presigned, skipping"$txtrst
            exit 1;
        fi
    fi

    [ $QUIET ] || echo $yellow"Certificate:"$txtrst" $CERT";

    [ -d $TMPDIR/$NAME ] && rm -rf $TMPDIR/$NAME
    mkdir -p $TMPDIR/$NAME
    trap "rm -rf $TMPDIR; exit" INT TERM EXIT
    cd $TMPDIR/$NAME
    unzip -q $BASE/$1
    for x in `find . -name "*.png" | grep -v "\.9.png$" | tr "\n" " "`
    do
        [ $QUIET ] || echo $grn"Crushing $x"$txtrst
        optimize_png $x
    done
    cp $BASE/$1 $BASE/$1.old

    [ $QUIET ] || echo $grn"Repacking apk.."$txtrst
    aapt p -0 .dat -0 .dict -0 .arsc -F $NAME .

    [ $QUIET ] || echo $ylw"Resigning with cert: `echo $CERT`"$txtrst

    [ $QUIET ] || echo java -Djava.library.path=$SIGNAPK_JNI_LIBRARY_PATH -jar $ANDROID_HOST_OUT/framework/signapk.jar $ANDROID_BUILD_TOP/$CERT $ANDROID_BUILD_TOP/$KEY $NAME signed_$NAME
    java -Djava.library.path=$SIGNAPK_JNI_LIBRARY_PATH -jar $ANDROID_HOST_OUT/framework/signapk.jar $ANDROID_BUILD_TOP/$CERT $ANDROID_BUILD_TOP/$KEY $NAME signed_$NAME 
    [ $QUIET ] || echo $grn"Zipalign.."$txtrst
    zipalign -f 4 signed_$NAME $BASE/$1
    if [ ! $QUIET ]; then
        ls -l $BASE/$1.old
        ls -l $BASE/$1
    fi
    rm $BASE/$1.old
else
    echo "Usage: $0 [apk file]"
fi
